# Generated by Django 4.2.10 on 2024-04-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_name_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notifEmail',
            field=models.BooleanField(default=False),
        ),
    ]
